// Códigos de erro tipados retornados pelas Cloud Functions.
// Nomenclatura: SCREAM_SNAKE_CASE, namespace por domínio.
export const CODIGOS_ERRO = {
  AUTH_NAO_AUTENTICADO: 'AUTH_NAO_AUTENTICADO',
  AUTH_SEM_ORG: 'AUTH_SEM_ORG',
  AUTH_SEM_PERMISSAO: 'AUTH_SEM_PERMISSAO',
  CAP_EXCEDIDO: 'CAP_EXCEDIDO',
  CAP_AVISO_90: 'CAP_AVISO_90',
  RATE_LIMIT: 'RATE_LIMIT',
  LLM_FALHA: 'LLM_FALHA',
  LLM_RESPOSTA_INVALIDA: 'LLM_RESPOSTA_INVALIDA',
  VALIDACAO_FALHOU: 'VALIDACAO_FALHOU',
  CONFIG_INVALIDA: 'CONFIG_INVALIDA',
  RECURSO_NAO_ENCONTRADO: 'RECURSO_NAO_ENCONTRADO',
  FLAG_DESLIGADA: 'FLAG_DESLIGADA',
} as const;

export type CodigoErro = (typeof CODIGOS_ERRO)[keyof typeof CODIGOS_ERRO];
